[phases.setup]
nixPkgs = [
  "php83", 
  "php83Packages.composer", 
  "php83Packages.gd", 
  "php83Packages.sodium", 
  "php83Packages.mysqlnd",
  "php83Packages.curl",
  "php83Packages.zip",
  "php83Packages.bcmath",
  "php83Packages.xml"
]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader", "php artisan config:cache"]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"
